# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish package to GitHub Packages
on:
#  release:
#    types: [created]
  workflow_dispatch:
    inputs:
      nexus_package:
        description: Publish to Nexus Packages
        required: false
        default: '1'
      github_package:
        description: Publish to GitHub Packages
        required: false
        default: '0'
      github_nexus_package:
        description: Publish to GitHub & Nexus Packages
        required: false
        default: '0'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish package to Nexus Packages
        if: ${{ github.event.inputs.nexus_package == '1' }}
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publish
        env:
          NEXUS_URL: https://f59f-191-97-56-158.ngrok.io/repository
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_INSECURE: false
      - name: Publish package to GitHub Packages
        if: ${{ github.event.inputs.github_package == '1' }}
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publish
        env:
          REPO_GITHUB_URL: https://maven.pkg.github.com/davisusanibar/gradle-kts-artifacts
          REPO_GITHUB_USERNAME: ${{ github.user }}
          REPO_GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish package to GitHub & Nexus Packages
        if: ${{ github.event.inputs.github_nexus_package == '1' }}
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publish
        env:
          REPO_GITHUB_URL: https://maven.pkg.github.com/davisusanibar/gradle-kts-artifacts
          REPO_GITHUB_USERNAME: ${{ github.user }}
          REPO_GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          NEXUS_URL: https://f59f-191-97-56-158.ngrok.io/repository
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_INSECURE: false
